/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetPostRequest struct {
	PostID string `json:"postID"`
}

// AssertGetPostRequestRequired checks if the required fields are not zero-ed
func AssertGetPostRequestRequired(obj GetPostRequest) error {
	elements := map[string]interface{}{
		"postID": obj.PostID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseGetPostRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetPostRequest (e.g. [][]GetPostRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetPostRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetPostRequest, ok := obj.(GetPostRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetPostRequestRequired(aGetPostRequest)
	})
}
