/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChangePermsRequest struct {
	PostID string `json:"postID"`
}

// AssertChangePermsRequestRequired checks if the required fields are not zero-ed
func AssertChangePermsRequestRequired(obj ChangePermsRequest) error {
	elements := map[string]interface{}{
		"postID": obj.PostID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseChangePermsRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ChangePermsRequest (e.g. [][]ChangePermsRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseChangePermsRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aChangePermsRequest, ok := obj.(ChangePermsRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertChangePermsRequestRequired(aChangePermsRequest)
	})
}
