/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type SubscribeRequest struct {
	WriterID string `json:"writerID"`
}

// AssertSubscribeRequestRequired checks if the required fields are not zero-ed
func AssertSubscribeRequestRequired(obj SubscribeRequest) error {
	elements := map[string]interface{}{
		"writerID": obj.WriterID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseSubscribeRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of SubscribeRequest (e.g. [][]SubscribeRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSubscribeRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSubscribeRequest, ok := obj.(SubscribeRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSubscribeRequestRequired(aSubscribeRequest)
	})
}
