/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ViewProfileRequest struct {
	Login string `json:"login"`
}

// AssertViewProfileRequestRequired checks if the required fields are not zero-ed
func AssertViewProfileRequestRequired(obj ViewProfileRequest) error {
	elements := map[string]interface{}{
		"login": obj.Login,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseViewProfileRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ViewProfileRequest (e.g. [][]ViewProfileRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseViewProfileRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aViewProfileRequest, ok := obj.(ViewProfileRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertViewProfileRequestRequired(aViewProfileRequest)
	})
}
