/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ViewProfileResponse struct {
	User User `json:"user"`

	Posts []Post `json:"posts"`

	Subscribed bool `json:"subscribed"`

	Self bool `json:"self"`
}

// AssertViewProfileResponseRequired checks if the required fields are not zero-ed
func AssertViewProfileResponseRequired(obj ViewProfileResponse) error {
	elements := map[string]interface{}{
		"user":       obj.User,
		"posts":      obj.Posts,
		"subscribed": obj.Subscribed,
		"self":       obj.Self,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertUserRequired(obj.User); err != nil {
		return err
	}
	for _, el := range obj.Posts {
		if err := AssertPostRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseViewProfileResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ViewProfileResponse (e.g. [][]ViewProfileResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseViewProfileResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aViewProfileResponse, ok := obj.(ViewProfileResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertViewProfileResponseRequired(aViewProfileResponse)
	})
}
