/*
 * API for ppo project
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DeletePostRequest struct {
	PostID string `json:"postID"`
}

// AssertDeletePostRequestRequired checks if the required fields are not zero-ed
func AssertDeletePostRequestRequired(obj DeletePostRequest) error {
	elements := map[string]interface{}{
		"postID": obj.PostID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDeletePostRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DeletePostRequest (e.g. [][]DeletePostRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDeletePostRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDeletePostRequest, ok := obj.(DeletePostRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDeletePostRequestRequired(aDeletePostRequest)
	})
}
